### ISSUE TITLE
Pre-Style Babel/WebPack Long Loads

### ISSUE THREAD

**Issue by dmhalejr** [soluml/babel-plugin-pre-style#1]
When leveraging pre-style we are running into 10 min.+ for 1400 modules when compiling prestyled components. 

```
[BS] Serving files from: src/client
webpack: wait until bundle finished: /index.html
File _prestyle.scss created.
File _prestyle.scss.classNames.js created.
  build [==========          ] 50%webpack: wait until bundle finished: /index.html
  build [=============       ] 65%webpack: wait until bundle finished: /index.html
  build [=============       ] 65%webpack: wait until bundle finished: /index.html
webpack: wait until bundle finished: /index.html
Build completed in 606.456s

webpack built 6cf501f89885f7ccfcdd in 606460ms
Hash: 6cf501f89885f7ccfcdd
Version: webpack 3.6.0
Time: 606460ms
```
A couple of questions:
1) Is this just the nature of compiling prestyle? 
2) Is there any way to alleviate this issue? 
3) If `no` to Question #2,  is there an alternative stylization module you'd recommend?

**Comment by soluml** [comment]
1. Partially. Pre-Style will be slower because it has several processes (normalizing, atomizing, etc.) it runs through with each CSS Block. It's going to be slower during build time than other CSS-in-JS libs because it does all the work ahead of time.  In browser, I'm not sure Pre-Style can be beat by other libs without a similar architecture.

2. Definitely. A few things: 
  - First off, reducing the number of ```PreStyle`...css...` ``` blocks will help. But, that's obviously not always an option.
  - Second, when you say 1400 modules, do you mean 1400 individual files all with Pre-Style blocks in them? I haven't done anything of that scope with Pre-Style yet so I haven't run into any real perf. issues.  Do make sure that that Pre-Style is only looking through files that it needs to instead of analyzing tons of files it doesn't need to looking for PreStyle blocks.
  - Third, if you do have a ton of files, could you produce a test case repo for me to pull down and run?  If so, I can probably find some heavy perf. improvements for you!

3. The common choice these days is Styled Components.  It's a pretty good library, but it doesn't beat Pre-Style in end-user perf. 🥇
